name: get
on: 
  schedule:
    - cron: '0 0 * * 0'
  push:
    branches: 
      - main

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
    - name: Download
      run: |
        curl https://image.thum.io/get/width/1024/crop/768/https://jerryc.me/ -o jerryc.me.jpg
        curl https://image.thum.io/get/width/1024/crop/768/https://butterfly.js.org/ -o butterfly.js.org.jpg
        curl https://image.thum.io/get/width/1024/crop/768/https://chen-shang.top/ -o chen-shang.top.jpg
        curl https://image.thum.io/get/width/1024/crop/768/https://blog.zhheo.com/ -o blog.zhheo.com.jpg
        curl https://image.thum.io/get/width/1024/crop/768/https://alexcld.com/ -o alexcld.com.jpg
        curl https://image.thum.io/get/width/1024/crop/768/https://www.hack-gov.com.cn/ -o www.hack-gov.com.cn.jpg
        curl https://image.thum.io/get/width/1024/crop/768/https://zfe.one/ -o zfe.one.jpg
        curl https://image.thum.io/get/width/1024/crop/768/https://www.maxin-blog.com/ -o www.maxin-blog.com.jpg
        curl https://image.thum.io/get/width/1024/crop/768/https://akilar.top/ -o akilar.top.jpg
        curl https://image.thum.io/get/width/1024/crop/768/https://www.iftiger.com/ -o www.iftiger.com.jpg
        curl https://image.thum.io/get/width/1024/crop/768/https://blog.imzjw.cn/ -o blog.imzjw.cn.jpg
        curl https://image.thum.io/get/width/1024/crop/768/https://www.antmoe.com/ -o www.antmoe.com.jpg
        curl https://image.thum.io/get/width/1024/crop/768/https://www.lete114.top/ -o www.lete114.top.jpg
        curl https://image.thum.io/get/width/1024/crop/768/https://wr0926.ml/ -o wr0926.ml.jpg
        curl https://image.thum.io/get/width/1024/crop/768/https://weilining.cf/ -o weilining.cf.jpg
        curl https://image.thum.io/get/width/1024/crop/768/https://blogs.ql-isaac.cn/ -o blogs.ql-isaac.cn.jpg
        curl https://image.thum.io/get/width/1024/crop/768/https://hexo.io/zh-cn/ -o hexo.io.jpg
        curl https://image.thum.io/get/width/1024/crop/768/https://blog.windandleaf.xyz/ -o blog.windandleaf.xyz.jpg
        curl https://image.thum.io/get/width/1024/crop/768/https://imciraos.com/ -o imciraos.com.jpg
        curl https://image.thum.io/get/width/1024/crop/768/https://wtnl.xyz/ -o wtnl.xyz.jpg
        curl https://image.thum.io/get/width/1024/crop/768/https://blog.molipre.com/ -o blog.molipre.com.jpg
        curl https://image.thum.io/get/width/1024/crop/768/https://blog.keepdai.cn/ -o blog.keepdai.cn.jpg
        curl https://image.thum.io/get/width/1024/crop/768/https://aabbj.com/ -o aabbj.com.jpg
        curl https://image.thum.io/get/width/1024/crop/768/https://zykj.js.org/ -o zykj.js.org.jpg
        curl https://image.thum.io/get/width/1024/crop/768/https://jiazhibo.top/ -o jiazhibo.top.jpg
        curl https://image.thum.io/get/width/1024/crop/768/https://ogliu.com/ -o ogliu.com.jpg
        curl https://image.thum.io/get/width/1024/crop/768/https://bili33.top/ -o bili33.top.jpg
        curl https://image.thum.io/get/width/1024/crop/768/https://ethant.top/ -o ethant.top.jpg
        curl https://image.thum.io/get/width/1024/crop/768/https://blog.slqwq.cn/ -o blog.slqwq.cn.jpg
        curl https://image.thum.io/get/width/1024/crop/768/https://qcyblm.gitee.io/ -o qcyblm.gitee.io.jpg
        curl https://image.thum.io/get/width/1024/crop/768/https://blog.ccknbc.cc/ -o blog.ccknbc.cc.jpg
        curl https://image.thum.io/get/width/1024/crop/768/https://www.wo-ow.cn/ -o www.wo-ow.cn.jpg
        curl https://image.thum.io/get/width/1024/crop/768/https://sutianxin.top/ -o sutianxin.top.jpg
        curl https://image.thum.io/get/width/1024/crop/768/https://jiushiboy.top/ -o jiushiboy.top.jpg
        curl https://image.thum.io/get/width/1024/crop/768/https://blog.jannns.com/ -o blog.jannns.com.jpg
        curl https://image.thum.io/get/width/1024/crop/768/https://sianx.com/ -o sianx.com.jpg
        curl https://image.thum.io/get/width/1024/crop/768/https://ccs.zone/ -o ccs.zone.jpg
        curl https://image.thum.io/get/width/1024/crop/768/https://imlql.cn/ -o imlql.cn.jpg
        curl https://purge.jsdelivr.net/gh/ql-isaac/ScreenShot@gh-pages/*.*
        
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.TOKEN }}
        publish_dir: ./
